{
 "title": "Fraud Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Top 10 Scammers",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"fraud\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"fraud\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> group(columns: [\"userId\"])\r\n  |> sum(column: \"_value\")\r\n  |> group()"
    }
   ]
  },
  {
   "title": "RealTime Values",
   "type": "stat",
   "gridPos": { "h": 9, "w": 10, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"fraud\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"fraud\")\r\n  |> map(fn: (r) => ({\r\n    _value: r._value,\r\n    _time: r._time\r\n  }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> group()"
    }
   ]
  },
  {
   "title": "Lastest Fraud Transacations",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 5, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"fraud\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"fraud\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({\r\n    Amount: r._value,\r\n    UserId: r.userId,\r\n    Time: r._time\r\n  }))\r\n  |> group()"
    }
   ]
  }
 ]
}